language: node_js
node_js:
    - stable
deploy:
    provider: heroku
    app: myfirstapiheroku-nodejs
    api_key:
        secure: cqnqTJ9HHaBbyQGyyObCGQNm8ddIend9VzsOLoYC014KNPdCyAqiOIm1VFIEcZaf6uaYwx5t5l+LQygvBnn6+q0nFUL3MhwFlwUygHpukKucMH32nczQs4uWT7ze8fYh3tkp1PtPG9+ykfZLEwV0mGleUCaEWK7vPLA8DExb1iJoI1733Hjkp0uBpCfW3PejToC7AQS2BYmMdQ+pCErUDB5KiloNZ+7BI1l1VZ8AwF2Wq6SLfTRRk/NQ4IBzQM0OVGd8muN1zrl2FMBGP0H8sVXh6e5LkgeMKUm7VOaq+P+wUzz4rhucW40Hz1aDlaKkIf6rqip/yrp6g5/GyDyr35VP++mP2L4qILeFVcHvbCHkrbkC1bY3IyoVXTBMi8K1yq5405S9d0/MLJ5C+/jNcyB8i7jyQJzY+J31JXVhrv9pQAt4tr/YFmwlXaydVPKKYfotMDVfZM9HABRxaAFR/IkCTS2Y1RQaa9ijnfmGixapO6FsHd56UenwhX1ex93AtX2+xRU85Fu/3uKefrRe0sVginGPmWIUORTre7Yi1ukSArm+/tBYxwpwqMWtSX+xgf2QNEWRTTLDO3kLi0rxDq+GZfZhZcSdJgF0mWhwc4QiAMyEWO313jlKFRaMClE/dLPz0wGYK8fZUGe+PdwllAvtizJ9sE6D8GJu5ZlrHp0=