language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: myfirstapiheroku-nodejs
  api_key:
    secure: R/2PVduia0xqKvDodo15PH9Nbcpcx5cGoLZ/EIpIkB9ag7GklDS0PXPdmULnVwiKJad2SC6zuNXcyiUCQJk0AwHvB/K69HjTcvXQDTWxZ9ID8Nzse592PZ6gZS7oyvGK9VzykpdoAG07iH44rIwjRwubACusWcMyPo8161ecF+fvU1LV/Ep1Ydc5vTRZc12ZSM2UnByZJQr8/n7dXr40PKBxFEZmb8ZX906q6gP3tzoiPgMu70n2pQ3AHa1K6MnzNbhklEZeH92ubiSz/N+ntKhVPNTv+vymiJj+ONi6Swr7Aq2Phb2rnAE6odrRMLQpH2++SaVaAujgabloBJhdixhsgkEhT38WrOMos6ae6s+aofzK84ErwvhEOe0X82mJ576wqfBy2a7/wNmYDoAjmaj+dVuk/jgHnq5lZX9bWlv2+JxgFS1L9jOBnmmZSF2P7nDlnkjJ4LJO1LpfeUv9v3g2Q+sfso6YYGapVrQvZ8lRMG/yqbFrIb6UxqnitY6dJ+lAZThtSGsI87vMnmbUZcYhr1E37YHkl26ktrvEdyqg3mE6s1Mfh1UiENARgJ1HNOJAifkVEqNPDEWpgvFamfE+6ma4b46/zdJtX9Gm9wgo15RJM/NaN9TW9ipVHojo9J9b2L0fnIRZWhsgO2MinKxHjrCnNGlGfCo8tN5tGWM=
