language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: myfirstapiheroku-nodejs
  api_key:
    secure: YxwYHcHRkSNIFo4XePfQ0+IQ9/vAxdvAGOEDJd6zRVLY79X6Tp914+TSlCmXZ01Nsj1mQaU+73qQGSzCk56+DiH7NG5FwyhkaM7780qMwuTEOTqkAVrHtsxiKA/Hvl+EVZdP7XQ8r8ZlA+0lsLYNPBsmbuVdOcC2CB4XgIOpZ+gl6QGeu4Zj5yt3nqzAcVA+6W6JMFtkieaULEjkzvWL1BAS/vQ6SWTTuhBNt0u7Q76pl4JXaKAcgK06ngmpcw3t8B/7UqQDL4zcxjOTgR+/YMj5ZXBreETzmRaoSDlaybxEdSJqNIbX00xLaH9jFWfEN0Ri3XtUxo3leyFLbPBjl4nOkunIqJDTbl2mFv7jlp59wFfNEt9kpbhMLYgvLguGaTwog4vz9Kr0oiS61NWd0KXMy2TlRSMgMC52978eicuXdbO4U/A2BPcQdUXUojShB4ELZZjscfIVKjzWHpoo5hmEl7R2QFPQ6IAdlSucV0sPkaEmXDXLPx79C8v27jEDtKnhw4Teewrmk0KwrJqDkoruAtgEYvW5qeuqjNbKCIbcZg7wPQ0S8ur1hhaNM8zrA9r3ZLNVyORtx2RgB2seqnj0I2x2CxcOmh2fCgOXQV1DWdwrvt5GWf0lk1dCeKpIcKfNKkI+Plkfh9wi5ExtaCOHYBJ8yXBQ4c5kOP5ZCKc=
