version: "3"

services: 
  api:
    build: . # indicar el dockerfile "." es aquí
    depends_on: # mongo tiene que estar iniciado
      - mongo
    environment: 
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/test
      - APPLICATION_NAME="Share Your Idea"
      - JWT_SECRET=xxzzyy
      - CACHE_KEY="iam-a-api"
      - SWAGGER_DOC=swaggerPROD
    ports: 
      - "5000:5000"
  mongo:
    image: mongo
  
      